### ISSUE TITLE
Globaltoken wallet reset after few hours

### ISSUE THREAD

**Issue by gawaynX** [globaltoken/coinbinGLT#1]
Hey, my name is Joschua and iam new with Globaltokens.
I just downloaded the wallet and deposited coins, but a few hours later when i tried
to open the wallet again, it started to download again (showed your 23 weeks behind) and created a new wallet. I need Help

**Comment by gawaynX** [comment]
i guess this is the Log Data
2017/06/20-23:29:29.000605 25b8 Delete type=3 #1
2017/06/20-23:29:29.000668 1cb4 Level-0 table #5: started
2017/06/20-23:29:29.000685 1cb4 Level-0 table #5: 421592 bytes OK
2017/06/20-23:29:29.000685 1cb4 Delete type=0 #3
2017/06/20-23:29:29.000437 1cb4 Level-0 table #7: started
2017/06/20-23:29:29.000450 1cb4 Level-0 table #7: 422963 bytes OK
2017/06/20-23:29:29.000451 1cb4 Delete type=0 #4
2017/06/20-23:29:29.000211 1cb4 Level-0 table #9: started
2017/06/20-23:29:29.000229 1cb4 Level-0 table #9: 422873 bytes OK
2017/06/20-23:29:29.000229 1cb4 Delete type=0 #6
2017/06/20-23:29:29.000947 1cb4 Level-0 table #11: started
2017/06/20-23:29:29.000963 1cb4 Level-0 table #11: 422808 bytes OK
2017/06/20-23:29:29.000963 1cb4 Delete type=0 #8
2017/06/20-23:29:29.000677 1cb4 Level-0 table #13: started
2017/06/20-23:29:29.000684 1cb4 Level-0 table #13: 419701 bytes OK
2017/06/20-23:29:29.000684 1cb4 Delete type=0 #10
2017/06/20-23:29:29.000358 1cb4 Level-0 table #15: started
2017/06/20-23:29:29.000375 1cb4 Level-0 table #15: 417745 bytes OK
2017/06/20-23:29:29.000375 1cb4 Delete type=0 #12
2017/06/20-23:29:29.000376 1cb4 Compacting 4@0 + 1@1 files
2017/06/20-23:29:29.000393 1cb4 Generated table #16: 6621 keys, 923390 bytes
2017/06/20-23:29:29.000393 1cb4 Compacted 4@0 + 1@1 files => 923390 bytes
2017/06/20-23:29:29.000393 1cb4 compacted to: files[ 0 1 1 0 0 0 0 ]
2017/06/20-23:29:29.000393 1cb4 Delete type=2 #7
2017/06/20-23:29:29.000393 1cb4 Delete type=2 #9
2017/06/20-23:29:29.000393 1cb4 Delete type=2 #11
2017/06/20-23:29:29.000394 1cb4 Delete type=2 #13
2017/06/20-23:29:29.000394 1cb4 Delete type=2 #15
2017/06/20-23:29:29.000045 1cb4 Level-0 table #18: started
2017/06/20-23:29:29.000070 1cb4 Level-0 table #18: 417719 bytes OK
2017/06/20-23:29:29.000071 1cb4 Delete type=0 #14
2017/06/20-23:29:29.000752 1cb4 Level-0 table #20: started
2017/06/20-23:29:29.000765 1cb4 Level-0 table #20: 417808 bytes OK
2017/06/20-23:29:29.000765 1cb4 Delete type=0 #17
2017/06/20-23:29:29.000446 1cb4 Level-0 table #22: started
2017/06/20-23:29:29.000462 1cb4 Level-0 table #22: 417778 bytes OK
2017/06/20-23:29:29.000463 1cb4 Delete type=0 #19
2017/06/20-23:29:29.000129 1cb4 Level-0 table #24: started
2017/06/20-23:29:29.000142 1cb4 Level-0 table #24: 417783 bytes OK
2017/06/20-23:29:29.000142 1cb4 Delete type=0 #21
2017/06/20-23:29:29.000143 1cb4 Compacting 4@0 + 1@1 files
2017/06/20-23:29:29.000165 1cb4 Generated table #25: 11829 keys, 1653489 bytes
2017/06/20-23:29:29.000165 1cb4 Compacted 4@0 + 1@1 files => 1653489 bytes
2017/06/20-23:29:29.000166 1cb4 compacted to: files[ 0 1 1 0 0 0 0 ]
2017/06/20-23:29:29.000166 1cb4 Delete type=2 #16
2017/06/20-23:29:29.000166 1cb4 Delete type=2 #18
2017/06/20-23:29:29.000166 1cb4 Delete type=2 #20
2017/06/20-23:29:29.000166 1cb4 Delete type=2 #22
2017/06/20-23:29:29.000167 1cb4 Delete type=2 #24
2017/06/20-23:29:29.000836 1cb4 Level-0 table #27: started
2017/06/20-23:29:29.000854 1cb4 Level-0 table #27: 417844 bytes OK
2017/06/20-23:29:29.000854 1cb4 Delete type=0 #23
2017/06/20-23:29:29.000522 1cb4 Level-0 table #29: started
2017/06/20-23:29:29.000537 1cb4 Level-0 table #29: 417813 bytes OK
2017/06/20-23:29:29.000537 1cb4 Delete type=0 #26
2017/06/20-23:29:29.000229 1cb4 Level-0 table #31: started
2017/06/20-23:29:29.000265 1cb4 Level-0 table #31: 418169 bytes OK
2017/06/20-23:29:29.000265 1cb4 Delete type=0 #28
2017/06/20-23:29:29.000957 1cb4 Level-0 table #33: started
2017/06/20-23:29:29.000970 1cb4 Level-0 table #33: 419511 bytes OK
2017/06/20-23:29:29.000971 1cb4 Delete type=0 #30
2017/06/20-23:29:29.000971 1cb4 Compacting 4@0 + 1@1 files
2017/06/20-23:29:29.000995 1cb4 Generated table #34: 15270 keys, 2137612 bytes
2017/06/20-23:29:29.000003 1cb4 Generated table #35: 1767 keys, 247311 bytes
2017/06/20-23:29:29.000003 1cb4 Compacted 4@0 + 1@1 files => 2384923 bytes
2017/06/20-23:29:29.000003 1cb4 compacted to: files[ 0 2 1 0 0 0 0 ]
2017/06/20-23:29:29.000003 1cb4 Delete type=2 #25
2017/06/20-23:29:29.000003 1cb4 Delete type=2 #27
2017/06/20-23:29:29.000003 1cb4 Delete type=2 #29
2017/06/20-23:29:29.000004 1cb4 Delete type=2 #31
2017/06/20-23:29:29.000004 1cb4 Delete type=2 #33
2017/06/20-23:29:29.000682 1cb4 Level-0 table #37: started
2017/06/20-23:29:29.000697 1cb4 Level-0 table #37: 417682 bytes OK
2017/06/20-23:29:29.000698 1cb4 Delete type=0 #32

**Comment by gawaynX** [comment]
But i deposited the coins 2017/06/20-15:03:33 and opened the wallet a few times about that time

**Comment by gawaynX** [comment]
GQqh5tm8jLrte3ZHNyJm58bmBN8eFMmchp that was my Walletadress, before it reseted

**Comment by gawaynX** [comment]
@globaltoken  I need Help please

**Comment by globaltoken** [comment]
The Android Wallet?

**Comment by gawaynX** [comment]
no the Windows Wallet.

**Comment by globaltoken** [comment]
Hey,

We have a new Windows Wallet could you try it out ?
